In [ ]:
!pip install scikit-plot

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import GradientBoostingClassifier
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import RandomizedSearchCV
import scikitplot as skplt

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


In [ ]:
train = pd.read_csv("/content/IEE520_Train.csv")
test = pd.read_csv("/content/IEE520_Test.csv")

Dealing with Missing Values

In [ ]:
train['x1'].value_counts()

0       7033
1        822
4        603
None     578
5        369
2        320
3        267
6          5
7          3
Name: x1, dtype: int64

In [ ]:
test['x1'].value_counts()

0       3530
1        377
4        313
None     280
2        187
5        184
3        126
6          2
7          1
Name: x1, dtype: int64

In [ ]:
train['x1']=train['x1'].replace("None",'8')
test['x1']=test['x1'].replace("None",'8')

In [ ]:
train['x4'].value_counts()

1       1268
4       1234
5       1226
8       1120
3       1108
2       1022
7        613
None     581
10       479
6        455
9        338
0        324
12       185
11        47
Name: x4, dtype: int64

In [ ]:
test['x4'].value_counts()

1       669
4       653
3       612
5       600
8       566
2       489
7       296
None    281
10      232
6       200
9       140
0       135
12       94
11       32
13        1
Name: x4, dtype: int64

In [ ]:
train['x4']=train['x4'].replace("None",'13')
test['x4']=test['x4'].replace("None",'13')

In [ ]:
train['x8'].value_counts()

0       8919
20       197
None     174
15        80
5         46
3         46
4         43
7         32
12        32
36        29
8         27
2         25
31        25
10        24
11        24
16        23
29        20
28        20
24        20
21        18
19        16
18        15
17        14
13        13
27        12
22        11
9          9
26         9
32         9
38         8
35         8
37         6
14         6
23         6
1          5
25         5
33         5
6          5
39         5
34         5
30         3
40         1
Name: x8, dtype: int64

In [ ]:
test['x8'].value_counts()

0       4486
20        97
None      92
15        30
36        21
3         20
12        20
5         19
4         16
11        13
17        13
24        11
10        11
28        10
29        10
16        10
19        10
2          9
31         9
7          9
18         8
8          8
32         7
27         6
23         6
13         6
21         6
38         6
26         5
9          4
6          4
37         3
1          3
22         2
33         2
14         2
39         2
35         1
25         1
30         1
34         1
Name: x8, dtype: int64

In [ ]:
train['x8']=train['x8'].replace("None",'41')
test['x8']=test['x8'].replace("None",'41')

In [ ]:
#Train
X = train.iloc[ :, : -1].values
Y = train.iloc[ :, -1].values

Handling Class imbalance

In [ ]:
np.unique(Y,return_counts=True)

(array([0, 1]), array([7580, 2420]))

In [ ]:
X_new, y_new = SMOTE().fit_sample(X,Y)
y_new = pd.DataFrame(y_new)
X_new = pd.DataFrame(X_new)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
np.unique(y_new,return_counts=True)

(array([0, 1]), array([7580, 7580]))

Fitting the Model

In [ ]:
model = GradientBoostingClassifier(max_depth=35,min_samples_split=10,min_samples_leaf=7,learning_rate=0.1,n_estimators=200)
model.fit(X_new, y_new)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/_gb.py:1454: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=35,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=7, min_samples_split=10,
                           min_weight_fraction_leaf=0.0, n_estimators=200,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

Test data

In [ ]:
test

instance x1  x2  x3  x4  x5  ...  x18       x19   x20    x21   x22   y
0            1  8   0   1  13   1  ...  126  0.692012  7.39  12.42  5.81 NaN
1            2  3   6   2   8   3  ...  173  2.548396  4.28  11.79  7.58 NaN
2            3  0   0   0   5   2  ...  126  2.052980  5.14  11.58  8.96 NaN
3            4  0   3   0   1   2  ...  126  1.025860  3.90  11.79  5.20 NaN
4            5  4   3   2   8   3  ...  126  0.798833  4.68  10.15  6.59 NaN
...        ... ..  ..  ..  ..  ..  ...  ...       ...   ...    ...   ...  ..
4995      4996  8  11   2  13   3  ...   94  2.088921  4.55  11.61  9.63 NaN
4996      4997  2   2   2   9   1  ...   94  3.912302  3.39   9.76  7.41 NaN
4997      4998  4  10   2   5   1  ...  173  2.904148  5.34   7.11  7.00 NaN
4998      4999  3   3   3   4   5  ...  126  1.618468  3.92   7.90  6.35 NaN
4999      5000  0   3   2   1   3  ...  126  1.884710  5.15  12.14  7.52 NaN

[5000 rows x 24 columns]

In [ ]:
instance = test['instance']

In [ ]:
instance

0          1
1          2
2          3
3          4
4          5
        ... 
4995    4996
4996    4997
4997    4998
4998    4999
4999    5000
Name: instance, Length: 5000, dtype: int64

In [ ]:
test.drop(['instance','y'],axis=1,inplace=True)

In [ ]:
#Predict on Test Data
y_pred = model.predict(test)

In [ ]:
y_pred

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
np.unique(y_pred,return_counts=True)

(array([0, 1]), array([3918, 1082]))

In [ ]:
y = pd.Series(y_pred)
result=pd.concat([instance, y], axis=1)

In [ ]:
result.head()

instance  0
0         1  0
1         2  0
2         3  1
3         4  0
4         5  0

In [ ]:
result.to_csv('BMI555IEE520Results2020AshishSanthaKumar.csv', index=False)